using Newtonsoft.Json.Linq;
using PoloniexWeb.Helpers;
using PoloniexWeb.Interfaces;
using PoloniexWeb.Models;
using PoloniexWeb.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace PoloniexWeb.Controllers
{
    public class HomeController : Controller
    {
        public HomeController()
        {
            StatisticService = new StatisticService();
        }
        private IStatisticService StatisticService { get; set; }

        List<SelectListItem> PoloniexPairs = new List<SelectListItem>
        {
            new SelectListItem { Text = "Ничего не выбрано",  Value = "Ничего не выбрано"},
            new SelectListItem { Text = "BTC_BCN",  Value = "BTC_BCN"},
            new SelectListItem { Text = "BTC_BELA", Value = "BTC_BELA"},
            new SelectListItem { Text = "BTC_BLK",  Value = "BTC_BLK"},
            new SelectListItem { Text = "BTC_BTCD", Value = "BTC_BTCD"},
            new SelectListItem { Text = "BTC_BTM",  Value = "BTC_BTM"},
            new SelectListItem { Text = "BTC_BTS",  Value = "BTC_BTS"},
            new SelectListItem { Text = "BTC_BURST",Value = "BTC_BURST"},
            new SelectListItem { Text = "BTC_CLAM", Value = "BTC_CLAM"},
            new SelectListItem { Text = "BTC_DASH", Value = "BTC_DASH"},
            new SelectListItem { Text = "BTC_DGB",  Value = "BTC_DGB"},
            new SelectListItem { Text = "BTC_DOGE", Value = "BTC_DOGE"},
            new SelectListItem { Text = "BTC_EMC2", Value = "BTC_EMC2"},
            new SelectListItem { Text = "BTC_FLDC", Value = "BTC_FLDC"},
            new SelectListItem { Text = "BTC_FLO",  Value = "BTC_FLO"},
            new SelectListItem { Text = "BTC_GAME", Value = "BTC_GAME"},
            new SelectListItem { Text = "BTC_GRC",  Value = "BTC_GRC"},
            new SelectListItem { Text = "BTC_HUC",  Value = "BTC_HUC"},
            new SelectListItem { Text = "BTC_LTC",  Value = "BTC_LTC"},
            new SelectListItem { Text = "BTC_MAID", Value = "BTC_MAID"},
            new SelectListItem { Text = "BTC_OMNI", Value = "BTC_OMNI"},
            new SelectListItem { Text = "BTC_NAUT", Value = "BTC_NAUT"},
            new SelectListItem { Text = "BTC_NAV",  Value = "BTC_NAV"},
            new SelectListItem { Text = "BTC_NEOS", Value = "BTC_NEOS"},
            new SelectListItem { Text = "BTC_NMC",  Value = "BTC_NMC"},
            new SelectListItem { Text = "BTC_NOTE", Value = "BTC_NOTE"},
            new SelectListItem { Text = "BTC_NXT",  Value = "BTC_NXT"},
            new SelectListItem { Text = "BTC_PINK", Value = "BTC_PINK"},
            new SelectListItem { Text = "BTC_POT",  Value = "BTC_POT"},
            new SelectListItem { Text = "BTC_PPC",  Value = "BTC_PPC"},
            new SelectListItem { Text = "BTC_RIC",  Value = "BTC_RIC"},
            new SelectListItem { Text = "BTC_SJCX", Value = "BTC_SJCX"},
            new SelectListItem { Text = "BTC_STR",  Value = "BTC_STR"},
            new SelectListItem { Text = "BTC_SYS",  Value = "BTC_SYS"},
            new SelectListItem { Text = "BTC_VIA",  Value = "BTC_VIA"},
            new SelectListItem { Text = "BTC_XVC",  Value = "BTC_XVC"},
            new SelectListItem { Text = "BTC_VRC",  Value = "BTC_VRC"},
            new SelectListItem { Text = "BTC_VTC",  Value = "BTC_VTC"},
            new SelectListItem { Text = "BTC_XBC",  Value = "BTC_XBC"},
            new SelectListItem { Text = "BTC_XCP",  Value = "BTC_XCP"},
            new SelectListItem { Text = "BTC_XEM",  Value = "BTC_XEM"},
            new SelectListItem { Text = "BTC_XMR",  Value = "BTC_XMR"},
            new SelectListItem { Text = "BTC_XPM",  Value = "BTC_XPM"},
            new SelectListItem { Text = "BTC_XRP",  Value = "BTC_XRP"},
            new SelectListItem { Text = "USDT_BTC", Value = "USDT_BTC"},
            new SelectListItem { Text = "USDT_DASH",Value = "USDT_DASH"},
            new SelectListItem { Text = "USDT_LTC", Value = "USDT_LTC"},
            new SelectListItem { Text = "USDT_NXT", Value = "USDT_NXT"},
            new SelectListItem { Text = "USDT_STR", Value = "USDT_STR"},
            new SelectListItem { Text = "USDT_XMR", Value = "USDT_XMR"},
            new SelectListItem { Text = "USDT_XRP", Value = "USDT_XRP"},
            new SelectListItem { Text = "XMR_BCN",  Value = "XMR_BCN"},
            new SelectListItem { Text = "XMR_BLK",  Value = "XMR_BLK"},
            new SelectListItem { Text = "XMR_BTCD", Value = "XMR_BTCD"},
            new SelectListItem { Text = "XMR_DASH", Value = "XMR_DASH"},
            new SelectListItem { Text = "XMR_LTC",  Value = "XMR_LTC"},
            new SelectListItem { Text = "XMR_MAID", Value = "XMR_MAID"},
            new SelectListItem { Text = "XMR_NXT",  Value = "XMR_NXT"},
            new SelectListItem { Text = "BTC_ETH",  Value = "BTC_ETH"},
            new SelectListItem { Text = "USDT_ETH", Value = "USDT_ETH"},
            new SelectListItem { Text = "BTC_SC",   Value = "BTC_SC"},
            new SelectListItem { Text = "BTC_BCY",  Value = "BTC_BCY"},
            new SelectListItem { Text = "BTC_EXP",  Value = "BTC_EXP"},
            new SelectListItem { Text = "BTC_FCT",  Value = "BTC_FCT"},
            new SelectListItem { Text = "BTC_RADS", Value = "BTC_RADS"},
            new SelectListItem { Text = "BTC_AMP",  Value = "BTC_AMP"},
            new SelectListItem { Text = "BTC_DCR",  Value = "BTC_DCR"},
            new SelectListItem { Text = "BTC_LSK",  Value = "BTC_LSK"},
            new SelectListItem { Text = "ETH_LSK",  Value = "ETH_LSK"},
            new SelectListItem { Text = "BTC_LBC",  Value = "BTC_LBC"},
            new SelectListItem { Text = "BTC_STEEM",Value = "BTC_STEEM"},
            new SelectListItem { Text = "ETH_STEEM",Value = "ETH_STEEM"},
            new SelectListItem { Text = "BTC_SBD",  Value = "BTC_SBD"},
            new SelectListItem { Text = "BTC_ETC",  Value = "BTC_ETC"},
            new SelectListItem { Text = "ETH_ETC",  Value = "ETH_ETC"},
            new SelectListItem { Text = "USDT_ETC", Value = "USDT_ETC"},
            new SelectListItem { Text = "BTC_REP",  Value = "BTC_REP"},
            new SelectListItem { Text = "USDT_REP", Value = "USDT_REP"},
            new SelectListItem { Text = "ETH_REP",  Value = "ETH_REP"},
            new SelectListItem { Text = "BTC_ARDR", Value = "BTC_ARDR"},
            new SelectListItem { Text = "BTC_ZEC",  Value = "BTC_ZEC"},
            new SelectListItem { Text = "ETH_ZEC",  Value = "ETH_ZEC"},
            new SelectListItem { Text = "USDT_ZEC", Value = "USDT_ZEC"},
            new SelectListItem { Text = "XMR_ZEC",  Value = "XMR_ZEC"},
            new SelectListItem { Text = "BTC_STRAT",Value = "BTC_STRAT"},
            new SelectListItem { Text = "BTC_NXC",  Value = "BTC_NXC"},
            new SelectListItem { Text = "BTC_PASC", Value = "BTC_PASC"},
            new SelectListItem { Text = "BTC_GNT",  Value = "BTC_GNT"},
            new SelectListItem { Text = "ETH_GNT",  Value = "ETH_GNT"},
            new SelectListItem { Text = "BTC_GNO",  Value = "BTC_GNO"},
            new SelectListItem { Text = "ETH_GNO",  Value = "ETH_GNO"}
        };
        List<SelectListItem> CEXPairs = new List<SelectListItem>
        {
            new SelectListItem { Text = "Ничего не выбрано",  Value = "Ничего не выбрано"},
            new SelectListItem { Text = "BTC_USD",  Value = "BTC:USD"},
            new SelectListItem { Text = "BCH_USD",  Value = "BCH:USD"},
            new SelectListItem { Text = "ETH_USD",  Value = "ETH:USD"},
            new SelectListItem { Text = "BTC_EUR",  Value = "BTC:EUR"},
            new SelectListItem { Text = "BCH_EUR",  Value = "BCH:EUR"},
            new SelectListItem { Text = "ETH_EUR",  Value = "ETH:EUR"},
            new SelectListItem { Text = "BTC_GBP",  Value = "BTC:GBP"},
            new SelectListItem { Text = "BCH_GBP",  Value = "BCH:GBP"},
            new SelectListItem { Text = "ETH_GBP",  Value = "ETH:GBP"},
            new SelectListItem { Text = "BCH_BTC",  Value = "BCH:BTC"},
            new SelectListItem { Text = "GHS_BTC",  Value = "GHS:BTC"},
            new SelectListItem { Text = "ETH_BTC",  Value = "ETH:BTC"},
            new SelectListItem { Text = "BTC_RUB",  Value = "BTC:RUB"}
        };
        List<SelectListItem> OKCoinPairs = new List<SelectListItem>
        {
            new SelectListItem { Text = "Ничего не выбрано",  Value = "Ничего не выбрано"},
            new SelectListItem { Text = "BTC_USD",  Value = "BTC_USD"},
            new SelectListItem { Text = "LTC_USD",  Value = "LTC_USD"},
            new SelectListItem { Text = "ETH_USD",  Value = "ETH_USD"}
        };
        List<SelectListItem> BittrexPairs = new List<SelectListItem>
        {
            new SelectListItem { Text = "Ничего не выбрано",  Value = "Ничего не выбрано"},
            new SelectListItem { Text = "BTC-LTC", Value = "BTC-LTC"},
            new SelectListItem { Text = "BTC-DOGE", Value = "BTC-DOGE"},
            new SelectListItem { Text = "BTC-VTC", Value = "BTC-VTC"},
            new SelectListItem { Text = "BTC-PPC", Value = "BTC-PPC"},
            new SelectListItem { Text = "BTC-FTC", Value = "BTC-FTC"},
            new SelectListItem { Text = "BTC-RDD", Value = "BTC-RDD"},
            new SelectListItem { Text = "BTC-NXT", Value = "BTC-NXT"},
            new SelectListItem { Text = "BTC-DASH", Value = "BTC-DASH"},
            new SelectListItem { Text = "BTC-POT", Value = "BTC-POT"},
            new SelectListItem { Text = "BTC-BLK", Value = "BTC-BLK"},
            new SelectListItem { Text = "BTC-EMC2", Value = "BTC-EMC2"},
            new SelectListItem { Text = "BTC-XMY", Value = "BTC-XMY"},
            new SelectListItem { Text = "BTC-AUR", Value = "BTC-AUR"},
            new SelectListItem { Text = "BTC-EFL", Value = "BTC-EFL"},
            new SelectListItem { Text = "BTC-GLD", Value = "BTC-GLD"},
            new SelectListItem { Text = "BTC-SLR", Value = "BTC-SLR"},
            new SelectListItem { Text = "BTC-PTC", Value = "BTC-PTC"},
            new SelectListItem { Text = "BTC-GRS", Value = "BTC-GRS"},
            new SelectListItem { Text = "BTC-NLG", Value = "BTC-NLG"},
            new SelectListItem { Text = "BTC-RBY", Value = "BTC-RBY"},
            new SelectListItem { Text = "BTC-XWC", Value = "BTC-XWC"},
            new SelectListItem { Text = "BTC-MONA", Value = "BTC-MONA"},
            new SelectListItem { Text = "BTC-THC", Value = "BTC-THC"},
            new SelectListItem { Text = "BTC-ENRG", Value = "BTC-ENRG"},
            new SelectListItem { Text = "BTC-ERC", Value = "BTC-ERC"},
            new SelectListItem { Text = "BTC-VRC", Value = "BTC-VRC"},
            new SelectListItem { Text = "BTC-CURE", Value = "BTC-CURE"},
            new SelectListItem { Text = "BTC-XBB", Value = "BTC-XBB"},
            new SelectListItem { Text = "BTC-XMR", Value = "BTC-XMR"},
            new SelectListItem { Text = "BTC-CLOAK", Value = "BTC-CLOAK"},
            new SelectListItem { Text = "BTC-START", Value = "BTC-START"},
            new SelectListItem { Text = "BTC-KORE", Value = "BTC-KORE"},
            new SelectListItem { Text = "BTC-XDN", Value = "BTC-XDN"},
            new SelectListItem { Text = "BTC-TRUST", Value = "BTC-TRUST"},
            new SelectListItem { Text = "BTC-NAV", Value = "BTC-NAV"},
            new SelectListItem { Text = "BTC-XST", Value = "BTC-XST"},
            new SelectListItem { Text = "BTC-BTCD", Value = "BTC-BTCD"},
            new SelectListItem { Text = "BTC-VIA", Value = "BTC-VIA"},
            new SelectListItem { Text = "BTC-UNO", Value = "BTC-UNO"},
            new SelectListItem { Text = "BTC-PINK", Value = "BTC-PINK"},
            new SelectListItem { Text = "BTC-IOC", Value = "BTC-IOC"},
            new SelectListItem { Text = "BTC-CANN", Value = "BTC-CANN"},
            new SelectListItem { Text = "BTC-SYS", Value = "BTC-SYS"},
            new SelectListItem { Text = "BTC-NEOS", Value = "BTC-NEOS"},
            new SelectListItem { Text = "BTC-DGB", Value = "BTC-DGB"},
            new SelectListItem { Text = "BTC-BURST", Value = "BTC-BURST"},
            new SelectListItem { Text = "BTC-EXCL", Value = "BTC-EXCL"},
            new SelectListItem { Text = "BTC-SWIFT", Value = "BTC-SWIFT"},
            new SelectListItem { Text = "BTC-DOPE", Value = "BTC-DOPE"},
            new SelectListItem { Text = "BTC-BLOCK", Value = "BTC-BLOCK"},
            new SelectListItem { Text = "BTC-ABY", Value = "BTC-ABY"},
            new SelectListItem { Text = "BTC-BYC", Value = "BTC-BYC"},
            new SelectListItem { Text = "BTC-XMG", Value = "BTC-XMG"},
            new SelectListItem { Text = "BTC-BLITZ", Value = "BTC-BLITZ"},
            new SelectListItem { Text = "BTC-BAY", Value = "BTC-BAY"},
            new SelectListItem { Text = "BTC-BTS", Value = "BTC-BTS"},
            new SelectListItem { Text = "BTC-FAIR", Value = "BTC-FAIR"},
            new SelectListItem { Text = "BTC-SPR", Value = "BTC-SPR"},
            new SelectListItem { Text = "BTC-VTR", Value = "BTC-VTR"},
            new SelectListItem { Text = "BTC-XRP", Value = "BTC-XRP"},
            new SelectListItem { Text = "BTC-GAME", Value = "BTC-GAME"},
            new SelectListItem { Text = "BTC-COVAL", Value = "BTC-COVAL"},
            new SelectListItem { Text = "BTC-NXS", Value = "BTC-NXS"},
            new SelectListItem { Text = "BTC-XCP", Value = "BTC-XCP"},
            new SelectListItem { Text = "BTC-BITB", Value = "BTC-BITB"},
            new SelectListItem { Text = "BTC-GEO", Value = "BTC-GEO"},
            new SelectListItem { Text = "BTC-FLDC", Value = "BTC-FLDC"},
            new SelectListItem { Text = "BTC-GRC", Value = "BTC-GRC"},
            new SelectListItem { Text = "BTC-FLO", Value = "BTC-FLO"},
            new SelectListItem { Text = "BTC-NBT", Value = "BTC-NBT"},
            new SelectListItem { Text = "BTC-MUE", Value = "BTC-MUE"},
            new SelectListItem { Text = "BTC-XEM", Value = "BTC-XEM"},
            new SelectListItem { Text = "BTC-CLAM", Value = "BTC-CLAM"},
            new SelectListItem { Text = "BTC-DMD", Value = "BTC-DMD"},
            new SelectListItem { Text = "BTC-GAM", Value = "BTC-GAM"},
            new SelectListItem { Text = "BTC-SPHR", Value = "BTC-SPHR"},
            new SelectListItem { Text = "BTC-OK" , Value = "BTC-OK" },
            new SelectListItem { Text = "BTC-SNRG", Value = "BTC-SNRG"},
            new SelectListItem { Text = "BTC-PKB", Value = "BTC-PKB"},
            new SelectListItem { Text = "BTC-CPC", Value = "BTC-CPC"},
            new SelectListItem { Text = "BTC-AEON", Value = "BTC-AEON"},
            new SelectListItem { Text = "BTC-ETH", Value = "BTC-ETH"},
            new SelectListItem { Text = "BTC-GCR", Value = "BTC-GCR"},
            new SelectListItem { Text = "BTC-TX" , Value = "BTC-TX" },
            new SelectListItem { Text = "BTC-BCY", Value = "BTC-BCY"},
            new SelectListItem { Text = "BTC-EXP", Value = "BTC-EXP"},
            new SelectListItem { Text = "BTC-INFX", Value = "BTC-INFX"},
            new SelectListItem { Text = "BTC-OMNI", Value = "BTC-OMNI"},
            new SelectListItem { Text = "BTC-AMP", Value = "BTC-AMP"},
            new SelectListItem { Text = "BTC-AGRS", Value = "BTC-AGRS"},
            new SelectListItem { Text = "BTC-XLM", Value = "BTC-XLM"},
            new SelectListItem { Text = "BTC-BTA", Value = "BTC-BTA"},
            new SelectListItem { Text = "USDT-BTC", Value = "USDT-BTC"},
            new SelectListItem { Text = "BTC-CLUB", Value = "BTC-CLUB"},
            new SelectListItem { Text = "BTC-VOX", Value = "BTC-VOX"},
            new SelectListItem { Text = "BTC-EMC", Value = "BTC-EMC"},
            new SelectListItem { Text = "BTC-FCT", Value = "BTC-FCT"},
            new SelectListItem { Text = "BTC-MAID", Value = "BTC-MAID"},
            new SelectListItem { Text = "BTC-EGC", Value = "BTC-EGC"},
            new SelectListItem { Text = "BTC-SLS", Value = "BTC-SLS"},
            new SelectListItem { Text = "BTC-RADS", Value = "BTC-RADS"},
            new SelectListItem { Text = "BTC-DCR", Value = "BTC-DCR"},
            new SelectListItem { Text = "BTC-SAFEX", Value = "BTC-SAFEX"},
            new SelectListItem { Text = "BTC-BSD", Value = "BTC-BSD"},
            new SelectListItem { Text = "BTC-XVG", Value = "BTC-XVG"},
            new SelectListItem { Text = "BTC-PIVX", Value = "BTC-PIVX"},
            new SelectListItem { Text = "BTC-XVC", Value = "BTC-XVC"},
            new SelectListItem { Text = "BTC-MEME", Value = "BTC-MEME"},
            new SelectListItem { Text = "BTC-STEEM", Value = "BTC-STEEM"},
            new SelectListItem { Text = "BTC-2GIVE", Value = "BTC-2GIVE"},
            new SelectListItem { Text = "BTC-LSK", Value = "BTC-LSK"},
            new SelectListItem { Text = "BTC-PDC", Value = "BTC-PDC"},
            new SelectListItem { Text = "BTC-BRK", Value = "BTC-BRK"},
            new SelectListItem { Text = "BTC-DGD", Value = "BTC-DGD"},
            new SelectListItem { Text = "ETH-DGD", Value = "ETH-DGD"},
            new SelectListItem { Text = "BTC-WAVES", Value = "BTC-WAVES"},
            new SelectListItem { Text = "BTC-RISE", Value = "BTC-RISE"},
            new SelectListItem { Text = "BTC-LBC", Value = "BTC-LBC"},
            new SelectListItem { Text = "BTC-SBD", Value = "BTC-SBD"},
            new SelectListItem { Text = "BTC-BRX", Value = "BTC-BRX"},
            new SelectListItem { Text = "BTC-DRACO", Value = "BTC-DRACO"},
            new SelectListItem { Text = "BTC-ETC", Value = "BTC-ETC"},
            new SelectListItem { Text = "ETH-ETC", Value = "ETH-ETC"},
            new SelectListItem { Text = "BTC-STRAT", Value = "BTC-STRAT"},
            new SelectListItem { Text = "BTC-UNB", Value = "BTC-UNB"},
            new SelectListItem { Text = "BTC-SYNX", Value = "BTC-SYNX"},
            new SelectListItem { Text = "BTC-TRIG", Value = "BTC-TRIG"},
            new SelectListItem { Text = "BTC-EBST", Value = "BTC-EBST"},
            new SelectListItem { Text = "BTC-VRM", Value = "BTC-VRM"},
            new SelectListItem { Text = "BTC-SEQ", Value = "BTC-SEQ"},
            new SelectListItem { Text = "BTC-XAUR", Value = "BTC-XAUR"},
            new SelectListItem { Text = "BTC-SNGLS", Value = "BTC-SNGLS"},
            new SelectListItem { Text = "BTC-REP", Value = "BTC-REP"},
            new SelectListItem { Text = "BTC-SHIFT", Value = "BTC-SHIFT"},
            new SelectListItem { Text = "BTC-ARDR", Value = "BTC-ARDR"},
            new SelectListItem { Text = "BTC-XZC", Value = "BTC-XZC"},
            new SelectListItem { Text = "BTC-NEO", Value = "BTC-NEO"},
            new SelectListItem { Text = "BTC-ZEC", Value = "BTC-ZEC"},
            new SelectListItem { Text = "BTC-ZCL", Value = "BTC-ZCL"},
            new SelectListItem { Text = "BTC-IOP", Value = "BTC-IOP"},
            new SelectListItem { Text = "BTC-DAR", Value = "BTC-DAR"},
            new SelectListItem { Text = "BTC-GOLOS", Value = "BTC-GOLOS"},
            new SelectListItem { Text = "BTC-HKG", Value = "BTC-HKG"},
            new SelectListItem { Text = "BTC-UBQ", Value = "BTC-UBQ"},
            new SelectListItem { Text = "BTC-KMD", Value = "BTC-KMD"},
            new SelectListItem { Text = "BTC-GBG", Value = "BTC-GBG"},
            new SelectListItem { Text = "BTC-SIB", Value = "BTC-SIB"},
            new SelectListItem { Text = "BTC-ION", Value = "BTC-ION"},
            new SelectListItem { Text = "BTC-LMC", Value = "BTC-LMC"},
            new SelectListItem { Text = "BTC-QWARK", Value = "BTC-QWARK"},
            new SelectListItem { Text = "BTC-CRW", Value = "BTC-CRW"},
            new SelectListItem { Text = "BTC-SWT", Value = "BTC-SWT"},
            new SelectListItem { Text = "BTC-TIME", Value = "BTC-TIME"},
            new SelectListItem { Text = "BTC-MLN", Value = "BTC-MLN"},
            new SelectListItem { Text = "BTC-ARK", Value = "BTC-ARK"},
            new SelectListItem { Text = "BTC-DYN", Value = "BTC-DYN"},
            new SelectListItem { Text = "BTC-TKS", Value = "BTC-TKS"},
            new SelectListItem { Text = "BTC-MUSIC", Value = "BTC-MUSIC"},
            new SelectListItem { Text = "BTC-DTB", Value = "BTC-DTB"},
            new SelectListItem { Text = "BTC-INCNT", Value = "BTC-INCNT"},
            new SelectListItem { Text = "BTC-GBYTE", Value = "BTC-GBYTE"},
            new SelectListItem { Text = "BTC-GNT", Value = "BTC-GNT"},
            new SelectListItem { Text = "BTC-NXC", Value = "BTC-NXC"},
            new SelectListItem { Text = "BTC-EDG", Value = "BTC-EDG"},
            new SelectListItem { Text = "BTC-LGD", Value = "BTC-LGD"},
            new SelectListItem { Text = "BTC-TRST", Value = "BTC-TRST"},
            new SelectListItem { Text = "ETH-GNT", Value = "ETH-GNT"},
            new SelectListItem { Text = "ETH-REP", Value = "ETH-REP"},
            new SelectListItem { Text = "USDT-ETH", Value = "USDT-ETH"},
            new SelectListItem { Text = "ETH-WINGS", Value = "ETH-WINGS"},
            new SelectListItem { Text = "BTC-WINGS", Value = "BTC-WINGS"},
            new SelectListItem { Text = "BTC-RLC", Value = "BTC-RLC"},
            new SelectListItem { Text = "BTC-GNO", Value = "BTC-GNO"},
            new SelectListItem { Text = "BTC-GUP", Value = "BTC-GUP"},
            new SelectListItem { Text = "BTC-LUN", Value = "BTC-LUN"},
            new SelectListItem { Text = "ETH-GUP", Value = "ETH-GUP"},
            new SelectListItem { Text = "ETH-RLC", Value = "ETH-RLC"},
            new SelectListItem { Text = "ETH-LUN", Value = "ETH-LUN"},
            new SelectListItem { Text = "ETH-SNGLS", Value = "ETH-SNGLS"},
            new SelectListItem { Text = "ETH-GNO", Value = "ETH-GNO"},
            new SelectListItem { Text = "BTC-APX", Value = "BTC-APX"},
            new SelectListItem { Text = "BTC-TKN", Value = "BTC-TKN"},
            new SelectListItem { Text = "ETH-TKN", Value = "ETH-TKN"},
            new SelectListItem { Text = "BTC-HMQ", Value = "BTC-HMQ"},
            new SelectListItem { Text = "ETH-HMQ", Value = "ETH-HMQ"},
            new SelectListItem { Text = "BTC-ANT", Value = "BTC-ANT"},
            new SelectListItem { Text = "ETH-TRST", Value = "ETH-TRST"},
            new SelectListItem { Text = "ETH-ANT", Value = "ETH-ANT"},
            new SelectListItem { Text = "BTC-SC" , Value = "BTC-SC"},
            new SelectListItem { Text = "ETH-BAT", Value = "ETH-BAT"},
            new SelectListItem { Text = "BTC-BAT", Value = "BTC-BAT"},
            new SelectListItem { Text = "BTC-ZEN", Value = "BTC-ZEN"},
            new SelectListItem { Text = "BTC-1ST", Value = "BTC-1ST"},
            new SelectListItem { Text = "BTC-QRL", Value = "BTC-QRL"},
            new SelectListItem { Text = "ETH-1ST", Value = "ETH-1ST"},
            new SelectListItem { Text = "ETH-QRL", Value = "ETH-QRL"},
            new SelectListItem { Text = "BTC-CRB", Value = "BTC-CRB"},
            new SelectListItem { Text = "ETH-CRB", Value = "ETH-CRB"},
            new SelectListItem { Text = "ETH-LGD", Value = "ETH-LGD"},
            new SelectListItem { Text = "BTC-PTOY", Value = "BTC-PTOY"},
            new SelectListItem { Text = "ETH-PTOY", Value = "ETH-PTOY"},
            new SelectListItem { Text = "BTC-MYST", Value = "BTC-MYST"},
            new SelectListItem { Text = "ETH-MYST", Value = "ETH-MYST"},
            new SelectListItem { Text = "BTC-CFI", Value = "BTC-CFI"},
            new SelectListItem { Text = "ETH-CFI", Value = "ETH-CFI"},
            new SelectListItem { Text = "BTC-BNT", Value = "BTC-BNT"},
            new SelectListItem { Text = "ETH-BNT", Value = "ETH-BNT"},
            new SelectListItem { Text = "BTC-NMR", Value = "BTC-NMR"},
            new SelectListItem { Text = "ETH-NMR", Value = "ETH-NMR"},
            new SelectListItem { Text = "ETH-TIME", Value = "ETH-TIME"},
            new SelectListItem { Text = "ETH-LTC", Value = "ETH-LTC"},
            new SelectListItem { Text = "ETH-XRP", Value = "ETH-XRP"},
            new SelectListItem { Text = "BTC-SNT", Value = "BTC-SNT"},
            new SelectListItem { Text = "ETH-SNT", Value = "ETH-SNT"},
            new SelectListItem { Text = "BTC-DCT", Value = "BTC-DCT"},
            new SelectListItem { Text = "BTC-XEL", Value = "BTC-XEL"},
            new SelectListItem { Text = "BTC-MCO", Value = "BTC-MCO"},
            new SelectListItem { Text = "ETH-MCO", Value = "ETH-MCO"},
            new SelectListItem { Text = "BTC-ADT", Value = "BTC-ADT"},
            new SelectListItem { Text = "ETH-ADT", Value = "ETH-ADT"},
            new SelectListItem { Text = "BTC-FUN", Value = "BTC-FUN"},
            new SelectListItem { Text = "ETH-FUN", Value = "ETH-FUN"},
            new SelectListItem { Text = "BTC-PAY", Value = "BTC-PAY"},
            new SelectListItem { Text = "ETH-PAY", Value = "ETH-PAY"},
            new SelectListItem { Text = "BTC-MTL", Value = "BTC-MTL"},
            new SelectListItem { Text = "ETH-MTL", Value = "ETH-MTL"},
            new SelectListItem { Text = "BTC-STORJ", Value = "BTC-STORJ"},
            new SelectListItem { Text = "ETH-STORJ", Value = "ETH-STORJ"},
            new SelectListItem { Text = "BTC-ADX", Value = "BTC-ADX"},
            new SelectListItem { Text = "ETH-ADX", Value = "ETH-ADX"},
            new SelectListItem { Text = "ETH-DASH", Value = "ETH-DASH"},
            new SelectListItem { Text = "ETH-SC" , Value = "ETH-SC"},
            new SelectListItem { Text = "ETH-ZEC", Value = "ETH-ZEC"},
            new SelectListItem { Text = "USDT-ZEC", Value = "USDT-ZEC"},
            new SelectListItem { Text = "USDT-LTC", Value = "USDT-LTC"},
            new SelectListItem { Text = "USDT-ETC", Value = "USDT-ETC"},
            new SelectListItem { Text = "USDT-XRP", Value = "USDT-XRP"},
            new SelectListItem { Text = "BTC-OMG", Value = "BTC-OMG"},
            new SelectListItem { Text = "ETH-OMG", Value = "ETH-OMG"},
            new SelectListItem { Text = "BTC-CVC", Value = "BTC-CVC"},
            new SelectListItem { Text = "ETH-CVC", Value = "ETH-CVC"},
            new SelectListItem { Text = "BTC-PART", Value = "BTC-PART"},
            new SelectListItem { Text = "BTC-QTUM", Value = "BTC-QTUM"},
            new SelectListItem { Text = "ETH-QTUM", Value = "ETH-QTUM"},
            new SelectListItem { Text = "ETH-XMR", Value = "ETH-XMR"},
            new SelectListItem { Text = "ETH-XEM", Value = "ETH-XEM"},
            new SelectListItem { Text = "ETH-XLM", Value = "ETH-XLM"},
            new SelectListItem { Text = "ETH-NEO", Value = "ETH-NEO"},
            new SelectListItem { Text = "USDT-XMR", Value = "USDT-XMR"},
            new SelectListItem { Text = "USDT-DASH", Value = "USDT-DASH"},
            new SelectListItem { Text = "ETH-BCC", Value = "ETH-BCC"},
            new SelectListItem { Text = "USDT-BCC", Value = "USDT-BCC"},
            new SelectListItem { Text = "BTC-BCC", Value = "BTC-BCC"},
            new SelectListItem { Text = "USDT-NEO", Value = "USDT-NEO"},
            new SelectListItem { Text = "ETH-WAVES", Value = "ETH-WAVES"},
            new SelectListItem { Text = "ETH-STRAT", Value = "ETH-STRAT"},
            new SelectListItem { Text = "ETH-DGB", Value = "ETH-DGB"},
            new SelectListItem { Text = "ETH-FCT", Value = "ETH-FCT"},
            new SelectListItem { Text = "ETH-BTS", Value = "ETH-BTS"}
        };

        public ActionResult Index()
        {
            return View();
        }
        [Authorize]
        public ActionResult Poloniex()
        {
            ViewBag.Pairs = PoloniexPairs;
            return View();
        }
        [Authorize]
        public ActionResult OKCoin()
        {
            ViewBag.Pairs = OKCoinPairs;
            return View();
        }
        [Authorize]
        public ActionResult CEX()
        {
            ViewBag.Pairs = CEXPairs;
            return View();
        }
        [Authorize]
        public ActionResult Sitemap()
        {
            var sitemapNodes = StaticDataHelper.GetSitemapNodes(Url);
            string xml = StaticDataHelper.GetSitemapDocument(sitemapNodes);
            return this.Content(xml, "text/xml", Encoding.UTF8);
        }
        [Authorize]
        public ActionResult Bittrex()
        {
            ViewBag.Pairs = BittrexPairs;
            return View();
        }
        [Authorize]
        public ActionResult GetData(string url)
        {
            return Json(StatisticService.GetData(url), JsonRequestBehavior.AllowGet);
        }
    }
}